stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "unix:///var/run/docker.sock"  # Используем локальный сокет Docker

build-job:
  stage: build
  image: node:22.11.0
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - docker info  # Проверяем доступность Docker
    - docker build -t employees .
  only:
    - main  # Замените на вашу основную ветку

deploy-job:
  stage: deploy
  script:
    - docker run -d -p 3007:80 employees
  only:
    - main  # Замените на вашу основную ветку
