stages:
  - build
  - deploy

# Сборка Docker образа
build_image:
  stage: build
  image: docker:latest
  services:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker build -t employees:latest .
    - docker tag employees:latest gitlab.ccenter.uz/root/employees-id-generator:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push gitlab.ccenter.uz/root/employees-id-generator:latest

# Развертывание образа
deploy_image:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Развертывание образа"
    # Используйте команду для развертывания, если она у вас настроена
    # Например:
    # - docker pull gitlab.ccenter.uz/root/employees-id-generator:latest
    # - docker-compose up -d
