stages:
  - build
  - deploy

# Определяем общие переменные
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  PROJECT_DIR: "/home/user/Projects/employees-id-generator"

build-job:
  stage: build
  script:
    - cd $PROJECT_DIR
    - docker build -t employees .
  only:
    - main  # Замените на основную ветку вашего проекта

deploy-job:
  stage: deploy
  script:
    - docker stop employees || true  # Останавливаем контейнер, если он уже запущен
    - docker rm employees || true    # Удаляем старый контейнер
    - docker run -d --name employees -p 3007:80 employees
  only:
    - main  # Замените на основную ветку вашего проекта
