stages:
  - deploy

deploy_to_production:
  stage: deploy
  only:
    - main  # Запускать только при изменениях в ветке main
  script:
    - cd /home/user/Projects/employees-id-generator
    - git pull origin main
    - npm install
    - npm run build
    - pm2 restart employees-id-generate
  tags:
    - deploy-runner  # Убедитесь, что ваш Runner привязан к серверу деплоя и имеет этот тег